openapi: 3.0.0
info:
  title: Stock Financial Data API
  version: 1.0.0
servers:
  - url: https://your-service-name.onrender.com
paths:
  /api/stock:
    get:
      summary: Get stock financial data
      parameters:
        - in: query
          name: symbols
          schema:
            type: string
          required: true
          description: Comma-separated stock tickers (e.g. AAPL,TSLA)
        - in: query
          name: report
          schema:
            type: string
            enum: [summary, income, balance, cashflow]
          required: false
          description: Report type
      responses:
        '200':
          description: Financial data for the stocks
          content:
            application/json:
              schema:
                type: object
