openapi: 3.0.0
info:
  title: GPT Financial + News API
  version: 1.0.0
servers:
  - url: https://gpt-finance-news-api.onrender.com
paths:
  /api/stock:
    get:
      operationId: getStockData
      summary: Get financial summary or full report of stock tickers
      parameters:
        - in: query
          name: symbols
          required: true
          schema:
            type: string
          description: Comma-separated tickers like AAPL,TSLA
        - in: query
          name: report
          required: false
          schema:
            type: string
            enum: [summary, income, balance, cashflow]
          description: Report type (summary is default)
      responses:
        '200':
          description: Stock financial data or report
          content:
            application/json:
              schema:
                type: object
  /api/news:
    get:
      operationId: getNews
      summary: Query news articles by keyword and time range from GNews
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
          description: Keyword to search for (e.g. Tesla)
        - in: query
          name: from
          required: false
          schema:
            type: string
          description: Start date (YYYY-MM-DD)
        - in: query
          name: to
          required: false
          schema:
            type: string
          description: End date (YYYY-MM-DD)
        - in: query
          name: lang
          required: false
          schema:
            type: string
            default: en
          description: Language (en, zh, etc.)
        - in: query
          name: max
          required: false
          schema:
            type: integer
            default: 10
          description: Maximum number of articles (up to 100)
      responses:
        '200':
          description: A list of news articles with title, url, published time
          content:
            application/json:
              schema:
                type: object
